#!/bin/sh
# Running this command will:
# 1) Perform initial flat xml extraction from content.xml in a sample odf document
# (unzipped from .odt - an actual article),
# 2) store in output xml file and
# 3) display with pygmentized (colorized) output in less (pager)
# Later, when all content have been extracted this way,
# the flat xml output will be manipulated in an XProc pipeline to massage the xml into JATS xml conformance
# This also includes performing RegEx pattern matching to auto-tag text citations and items in the reference list
saxon source/odf-exworthy-refs/content.xml flat_odf_xml_extract.xsl 2> err.log | tee flat-extract-output-exworthy-refs.xml | pygmentize -l xml | less -R
